### ISSUE TITLE
Question about server side rendering

### ISSUE THREAD

**Issue by enbits** [RyanCCollins/scalable-react-boilerplate#77] opened 2017-02-15 22:31 UTC
I noticed on the example website that comes with the kit that if you go to a route lets say 'about' it reloads the whole page. Is this by design to implement server side rendering on every route change?

**Comment by RyanCCollins** [comment] 2017-02-16 03:12
Hey @enbits thanks for getting in touch! 

This is by design.  The reason for this is because when you are building huge apps, which this boilerplate was meant to solve in a scalable way, the size of your bundle is generally a performance bottleneck.  We take the approach of chunking the bundle and using lazy loading of chunks per route to minimize the amount of work that the browser needs to do on each initial load.

With everything in Computer Science, there is a tradeoff to this approach, which is that you have to reload each chunk on each route transition.  There are a few methods to try to solve this that I have employed.  One of my favorites is to use Service worker to cache the bundles.  In fact this boilerplate has some configuration if you want to use Service Worker.  One requirement for that, however, is that you are running your server behind SSl, which the demo site is not.

Please let me know if this answers your question.  I'd be happy to try to explain it more in depth if you want.

**Comment by enbits** [comment] 2017-02-16 15:36
Thanks Ryan for the detailed response. 

Didn't realize you were using classic anchors on the Navbar component, but if react-router links are used instead you get client side rendering. Its really nice to have both options working out of the box.

Also the cli generator is very good. You made a complete framework, very good!

**Comment by RyanCCollins** [comment] 2017-02-16 16:02
Yeah, the grommet Anchor component recently added a path property that uses react router behind the scenes.  Sorry forgot to mention that, it's been a while since I've touched this demo site.  I'll have to refactor the navbar at some point to use the path vs href.  I'd like to upgrade to react router 4 soon anyways!

Glad it's working out for you and that you like the generators!

**Comment by RyanCCollins** [comment] 2017-02-18 15:13
Hey @enbits , I am going to close this issue, but feel free to keep the conversation going or reopen it if you have any more questions.

**Closed by RyanCCollins** 2017-02-18 15:13 UTC
